import Image from 'next/image'
import Link from 'next/link'
import { FiChevronDown } from 'react-icons/fi'
import { PiRocket } from 'react-icons/pi'

export const Hero = () => (
  <section className='w-full min-h-[60vh] xl:min-h-screen pt-[199px]'>
    <div className='container text-white flex flex-col items-center justify-center'>
      <p className='text-white-1 font-medium  text-[13px] xl:text-[15px] leading-[15px] xl:leading-[18px]'>
        WELCOME TO MONISWAP
      </p>
      <h1 className='font-medium mt-[31px]  text-[30px] xl:text-[45px] max-w-[600px] text-white leading-[36px] xl:leading-[54px] text-center'>
        The central hub for trading & liquidity marketplace on 🐻 Berachain
      </h1>

      <Link
        href='/swap'
        className='rounded-full bg-gradient-to-br mt-16 from-yellow-400 to-orange-500 p-5 w-[121px] h-[121px] flex items-center justify-center text-center flex-col gap-3 text-[12px] text-white my-5 leading-tight'
      >
        <PiRocket color='#fff' size={30} />
        <p className='text-sm capitalize'>swap</p>
      </Link>
      <div className='py-0 animate-bounce '>
        <FiChevronDown className='text-[20px] -mb-2 text-[--inverted-text]' />
        <FiChevronDown className='text-[20px] -mb-2 text-[--inverted-text]' />
        <FiChevronDown className='text-[20px] -mb-2 text-[--inverted-text]' />
        <FiChevronDown className='text-[20px] -mb-2 text-[--inverted-text]' />
      </div>
      <p className='text-[13px] xl:text-[15px] text-white-1 font-normal mt-16 leading-[15px] xl:leading-[18.15px] text-center max-w-[271px] sm:max-w-[350px] md:max-w-[550px] xl:max-w-[740px] '>
        Moniswap represents the next evolution of automated market makers (AMMs)
        and serves as the central liquidity hub for 🐻 Berachain. It integrates
        a robust liquidity incentive engine, a governance model based on
        vote-lock mechanisms. Leveraging the latest features from Velodrome V2,
        Moniswap NFTs vote to distribute token emissions and receive incentives
        and fees generated by the protocol.
      </p>
    </div>
  </section>
)
