import Image from "next/image";
import Link from "next/link";
import { FiChevronDown } from "react-icons/fi";
import { PiRocket } from "react-icons/pi";

export default function Home() {
  return (
    <main className="text-[--inverted-text] relative w-screen">
      <section className="w-full">
        <div className="flex w-full mx-auto items-center justify-center h-fit md:h-screen flex-col py-20 md:py-0">
          <div className="flex flex-col justify-center text-center">
            <h1 className="capitalize text-[--inverted-text] text-sm py-2">WELCOME TO MONISWAP</h1>
            <h1 className="max-w-[21ch] text-[30.5px] md:text-[45px] flex flex-col italic text-white md:leading-[50px] leading-[45px]">
              The central hub for trading &amp; liquidity marketplaces on
              <span className="justify-center flex items-center text-[45px]">
                <Image src="/images/berachain.svg" width={35} height={35} alt="Berachain" className="" />{" "}
                <h1 className="text-[30.5px] md:text-[45px]">Berachain.</h1>
              </span>
            </h1>
            <div className="text-center flex items-center justify-center my-10 flex-col">
              <Link
                href="/swap"
                className="rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 p-5 w-[100px] h-[100px] flex items-center justify-center text-center flex-col gap-3 text-[12px] text-white my-5 leading-tight"
              >
                <PiRocket color="#fff" size={30} />
                <p className="text-sm capitalize">swap</p>
              </Link>
              <div className="py-3">
                <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
                <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
                <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
                <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
              </div>
            </div>
          </div>
          <div className="w-[90%] md:w-1/2 mx-auto flex justify-center text-center">
            <p className="text-sm md:text-[15px] italic text-[--inverted-text]">
              Moniswap is a next-generation AMM designed to serve as Berachain&apos;s central liquidity hub, combining a
              powerful liquidity incentive engine, vote-lock governance model, and friendly user experience. Moniswap
              inherits the latest features from Velodrome V2. Moniswap NFTs vote to distribute token emissions and
              receive incentives and fees generated by the protocol.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full">
        <div className="mx-auto w-[90%] md:w-[1000px]">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="px-5 py-8 relative rounded-[10px] border border-[--border] text-[--inverted-text] text-sm">
              <h1>Stable & volatile</h1>
              <h1>Trading for Low Fees.</h1>
              <Image
                src="/images/star.png"
                width={30}
                height={30}
                alt="Stable & volatile"
                className="absolute top-2 right-2"
              />
            </div>
            <div className="px-5 py-8 relative rounded-[10px] border border-[--border] text-[--inverted-text] text-sm">
              <h1>100% of Protocol Incentives</h1>
              <h1>and Fees Go to Voters.</h1>
              <Image
                src="/images/star.png"
                width={30}
                height={30}
                alt="Stable & volatile"
                className="absolute top-2 right-2"
              />
            </div>
            <div className="px-5 py-8 relative rounded-[10px] border border-[--border] text-[--inverted-text] text-sm">
              <h1>Liquid Locked Positions</h1>
              <h1>in the Form of NFTs.</h1>
              <Image
                src="/images/star.png"
                width={30}
                height={30}
                alt="Stable & volatile"
                className="absolute top-2 right-2"
              />
            </div>
            <div className="px-5 py-8 relative rounded-[10px] border border-[--border] text-[--inverted-text] text-sm">
              <h1>Permissionless Pools,</h1>
              <h1>Gauges, and Incentives.</h1>
              <Image
                src="/images/star.png"
                width={30}
                height={30}
                alt="Stable & volatile"
                className="absolute top-2 right-2"
              />
            </div>
            <div className="px-5 py-8 relative rounded-[10px] border border-[--border] text-[--inverted-text] text-sm">
              <h1>Self-Optimizing</h1>
              <h1>Liquidity Flywheel.</h1>
              <Image
                src="/images/star.png"
                width={30}
                height={30}
                alt="Self-Optimizing"
                className="absolute top-2 right-2"
              />
            </div>
            <div className="px-5 py-8 relative rounded-[10px] border border-[--border] text-[--inverted-text] text-sm">
              <h1>Anti-dilution</h1>
              <h1>rebases for voters.</h1>
              <Image
                src="/images/star.png"
                width={30}
                height={30}
                alt="Stable & volatile"
                className="absolute top-2 right-2"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full">
        <div className="mx-auto md:w-[1000px] py-20 px-10 md:px-0">
          <div className="w-full justify-center flex flex-col items-center text-center">
            <h1 className="text-white text-[45px] italic">How it Works.</h1>
            <p className="text-sm mb-5">
              Crafted to incentivize contributors fostering the sustainable expansion of the protocol.
            </p>
            <Image src="/images/how_it_works.svg" width={700} height={500} alt="How it works" className="mt-8" />
          </div>
        </div>
      </section>
      <section className="w-full">
        <div className="mx-auto w-[90%]">
          <div className="w-full grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className=" bg-[rgba(30,30,30,1)]  overflow-hidden rounded-[15px]">
              <div className="h-60 min-h-60 relative px-5 py-10">
                <h1 className="text-white text-[20px] italic mb-5">Traders</h1>
                <p className="text-[12px] font-[400] leading-tight">
                  Exchange tokens with minimal slippage and pay some of the most competitive fees to MONI lockers.
                </p>
                <Image
                  src="/images/bea.png"
                  width={40}
                  height={40}
                  alt="Traders"
                  className="object-contain absolute top-2 right-5"
                />
              </div>
              <div className="w-full min-h-40 overflow-hidden">
                <Image src="/images/1.png" width={500} height={100} alt="Traders" className="object-contain" />
              </div>
            </div>
            <div className=" bg-[rgba(30,30,30,1)]  overflow-hidden rounded-[15px]">
              <div className="h-60 min-h-60 relative px-5 py-10">
                <h1 className="text-white text-[20px] italic mb-5">Liquidity Providers</h1>
                <p className="text-[12px] font-[400] leading-tight">
                  Deposit the tokens utilized for trading on Moniswap and earn MONI emissions as incentives.
                </p>
                <Image
                  src="/images/bea.png"
                  width={40}
                  height={40}
                  alt="Traders"
                  className="object-contain absolute top-2 right-5"
                />
              </div>
              <div className="w-full min-h-40 overflow-hidden">
                <Image src="/images/2.png" width={500} height={100} alt="Traders" className="object-contain" />
              </div>
            </div>
            <div className=" bg-[rgba(30,30,30,1)]  overflow-hidden rounded-[15px]">
              <div className="h-60 min-h-60 relative px-5 py-10">
                <h1 className="text-white text-[20px] italic mb-5">Protocols</h1>
                <p className="text-[12px] font-[400] leading-tight">
                  Provide incentives to veMONI voters, encouraging the attraction of votes and MONI emissions to their
                  pools, enabling the cost-effective establishment of liquidity.
                </p>
                <Image
                  src="/images/bea.png"
                  width={40}
                  height={40}
                  alt="Traders"
                  className="object-contain absolute top-2 right-5"
                />
              </div>
              <div className="w-full min-h-40 overflow-hidden">
                <Image src="/images/3.png" width={500} height={100} alt="Traders" className="object-contain" />
              </div>
            </div>
            <div className=" bg-[rgba(30,30,30,1)]  overflow-hidden rounded-[15px]">
              <div className="h-60 min-h-40 relative px-5 py-10">
                <h1 className="text-white text-[20px] italic mb-5">veMONI Voters</h1>
                <p className="text-[12px] font-[400] leading-tight">
                  Cast your vote to determine the pools that will accrue MONI emissions, and earn 100% of incentives and
                  fees for the selected pools. Any MONI holder has the option to lock their tokens and convert them into
                  veMONI.
                </p>
                <Image
                  src="/images/bea.png"
                  width={40}
                  height={40}
                  alt="Traders"
                  className="object-contain absolute top-2 right-5"
                />
              </div>
              <div className="w-full min-h-40 overflow-hidden">
                <Image src="/images/4.png" width={500} height={100} alt="Traders" className="object-contain" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full bg-[url('/images/bg.svg')] h-screen bg-no-repeat	bg-center my-20">
        <div className="flex w-full mx-auto items-center justify-center flex-col">
          <div className="-mt-10 ">
            <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
            <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
            <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
            <FiChevronDown className="text-[20px] -mb-2 text-[--inverted-text]" />
          </div>
          <div className="flex items-center h-[calc(100vh-100px)] flex-col  justify-center w-full">
            <Image src="/images/chain.png" width={90} height={30} alt="chain" className="my-5" />
            <h1 className="text-white text-[25px] italic text-center">Looking to get </h1>
            <h1 className="text-white text-[40px] italic text-center">Started on Moniswap?</h1>
            <Link
              href="/swap"
              className="rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 p-5 w-[100px] h-[100px] flex items-center justify-center text-center flex-col gap-3 text-[12px] text-white my-5 leading-tight"
            >
              <PiRocket color="#fff" size={25} />
              <p className="text-xs capitalize">onboarding guide</p>
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
